In [2]:
import numpy as np

Q1. Three students' marks arrived as three separate lists, and one old record arrived as text.

Tasks

Build one table from s1, s2 and s3.
From that table, print the number of students and the number of subjects as two separate numbers.
Print the total count of marks entries stored in the table.
Store the same table as decimals instead of whole numbers.
Convert old into a form where arithmetic works, then print the total marks of both students.
Attach old below the main table so that all five students sit in one table.

In [3]:
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

In [5]:

table=np.array([s1,s2,s3])
print(table)

tableShape=table.shape
print("no of student", tableShape[0])
print("no of subjects", tableShape[1])

print("total count", table.size)

tableFloat=table.astype("float32")
print(tableFloat)

oldForm=old.astype("int32")
print(oldForm)

finalTable=np.vstack((table,oldForm))
print(finalTable)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
no of student 3
no of subjects 4
total count 12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[[62 71 55 80]
 [49 58 66 73]]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


Q2. Templates and sequences
Tasks

Create a blank mark sheet for 6 students and 4 subjects, every entry starting at 0.
Create a table of the same size where every student is temporarily given 35.
A batch has roll numbers running from 101 to 130. Generate only the alternate roll numbers, and print how many were generated.
Split a 3-hour practical into 7 equally spaced time markers, including both the start and the end.
Create a 5 × 5 table that has 10 on the diagonal and 0 everywhere else.
Create a 4 × 4 table that has 100 on the diagonal and 35 everywhere else.

In [12]:
markSheet=np.zeros((6,4),dtype="int32")
print(markSheet)

tempSheet=np.full((6,4),35)
print(tempSheet)

rollNo=np.arange(101,131,2)
print(rollNo)

examTime=np.linspace(0,3,7)
print(examTime)

diaData=np.eye(5,dtype="int32")*10
print(diaData)

a=np.eye(4,dtype="int32")*65
b=np.full((4,4),35)

ans=a+b
print(ans)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


Q3. The attendance row
Tasks

Print the first and the last student's attendance without writing the class strength anywhere in your code.
Print the attendance of every alternate student, starting from the second one.
Print the last four values.
Reverse the row, then print every third value of the reversed row.
Change the attendance of the two middle students to 30 each.
Compare the first half of the row with the second half position by position, and print the difference.
Print the top three values of the row after reversing it.


In [ ]:
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

print("1st roll", present[0])
print("last roll", present[-1])

attendence=present[1::2]
print(attendence)

last4=present[-1:-5:-1]
print(last4)

rev=present[::-1]
print(rev[::3])

mid=len(present)//2
present[mid-1:mid+1]=30
print(present)

firstHalf=present[:mid]
secondHalf=present[mid:]
diff=secondHalf-firstHalf
print(diff)

print(rev[:3])



1st roll 22
last roll 23
[18 12 24 21 23]
[23 17 21  9]
[23  9 12 22]
[22 18 25 12 30 30  9 21 17 23]
1st [22 18 25 12 30]
2nd [30  9 21 17 23]
[ 8 -9 -4  5 -7]
[23 17 21]


Q4. Reading the mark sheet
The columns are Math, Physics, Chemistry and English.

Tasks

Print the Physics and Chemistry marks of the middle three students only.
Print the last subject's marks for the whole class.
Produce a table containing only the first and the last subject of every student.
Print the mark sheet with the students in reverse order.
Increase only the Chemistry marks of the whole class by 5, leaving the rest unchanged.
Print the mark that sits in the last row and the second-last column.
Produce a table of the last two students and their first two subjects.


In [20]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])


In [25]:
midStud=marks[1:4,1:3]
print(midStud)

lastSub=marks[:,-1]
print(lastSub)

table=marks[:,0::3]
print(table)

revMark=marks[::-1,::-1]
print(revMark)

marks[:,2]+=5
print(marks)

stud=marks[-1,-2]
print(stud)

mat=marks[-1:-3:-1,0:2]
print(mat)

[[30 98]
 [66 74]
 [92 55]]
[ 91  55 100  40  70]
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
[[ 70  62  48  30]
 [ 40  55  92  95]
 [100  74  66  88]
 [ 55  98  30  45]
 [ 91  60  85  72]]
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]
67
[[30 48]
 [95 92]]


Q5. Scholarship shortlisting
Tasks

Print the totals of students who scored above 250.
Print the totals of students scoring above 180 but below 250.
Print the totals of students who scored either below 150 or above 380.
Print how many students fall in the band of task 2.
Print the average of only those students who scored above 200.
Print the index position of every student below 150.
Print the highest total among the students who did not make the merit band of task1

In [26]:
totals = np.array([245, 310, 178, 392, 140, 265, 199, 155, 288, 132])

In [33]:
student1=totals[totals>250]
print(student1)

student2=totals[(totals>180) & (totals<250)]
print(student2)

student3=totals[(totals<150) | (totals>380)]
print(student3)

print(len(student2))

student4=totals[totals>200];
print(np.mean(student4))

student5=np.where(totals<150)
print(student5[0])

student6=totals[totals<=250]
print(np.max(student6))


[310 392 265 288]
[245 199]
[392 140 132]
2
300.0
[4 9]
245


Q6. After revaluation
Tasks

Increase every student's marks by 15% and round to 2 decimals.
After the increase, no student may show more than 100. Produce the corrected list.
Print how many students gained less than 10 marks from this increase.
The pass mark is 40. Print how many students were failing before the increase and how many after.
Print each student's marks as a percentage of the topper's marks, rounded to 1 decimal.
Print the total number of marks the school gave away in this revaluation.

In [34]:
marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])

In [40]:
newMarks=np.round(marks*1.15,2)
print(newMarks)

limitMarks= np.clip(newMarks, a_min=None, a_max=100)
print(limitMarks)

arr=limitMarks-marks
student1=arr[arr<10]
print(len(student1))

arr1=marks[marks<40]
print(len(arr1))

topperMark=np.max(marks)
stud=np.round((marks/topperMark)*100,1)
print(stud)

print(np.sum(arr))


[ 46.    63.25  71.3  101.2  109.25  37.95  81.65  66.7 ]
[ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]
6
1
[ 42.1  57.9  65.3  92.6 100.   34.7  74.7  61.1]
64.85000000000001


Q7. The result summary
Tasks

Print the class average and the middle value of the class.
Print the gap between the highest and the lowest marks.
Print the index positions of the topper and of the weakest student.
Print the second highest marks in the class.
Print how many students scored above the class average.
Print how many students lie within one standard deviation of the class average.
Print the class average after removing the topper.

In [49]:
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])

In [51]:
avg=np.mean(marks)
median=np.median(marks)
print(avg,median)

maxMark=np.max(marks)
minMark=np.min(marks)
print(maxMark-minMark)

topperPos=np.where(marks==maxMark)
print(topperPos[0][0])
weakPos=np.where(marks==minMark)
print(weakPos[0][0])

secondHigh=np.sort(marks)[-2]
print(secondHigh)

student1=marks[marks>avg]
print(len(student1))

std=np.std(marks)
lower=avg-std
high=avg+std
student2=marks[(marks>=lower) & (marks<=high)]
print(len(student2))


student3=marks[marks!=maxMark]
print(np.round(np.mean(student3),2))

65.9 69.5
65
3
4
91
6
5
62.67


Q8. Subject-wise and student-wise reports
Tasks

Print the average of each subject and the total of each student.
Print the index of the toughest subject for the class.
Print the index of the student who topped overall.
For every subject, print the marks of the student who topped that subject.
Print how many students scored above 60 in each subject.
Print the index of the subject in which the class marks are the most spread out.
Print the total marks of the student who scored the lowest in Chemistry.

In [53]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])

In [54]:
subject_averages = np.mean(marks, axis=0)
student_totals = np.sum(marks, axis=1)
print("Task 1:")
print(f"Average of each subject: {subject_averages}")
print(f"Total of each student: {student_totals}\n")

toughest_subject_idx = np.argmin(subject_averages)
print("Task 2:")
print(f"Index of toughest subject: {toughest_subject_idx}\n")


overall_topper_idx = np.argmax(student_totals)
print("Task 3:")
print(f"Index of overall topper: {overall_topper_idx}\n")


subject_toppers_marks = np.max(marks, axis=0)
print("Task 4:")
print(f"Highest marks in each subject: {subject_toppers_marks}\n")

above_60_count = np.sum(marks > 60, axis=0)
print("Task 5:")
print(f"Students scoring above 60 per subject: {above_60_count}\n")


most_spread_subject_idx = np.argmax(np.std(marks, axis=0))
print("Task 6:")
print(f"Index of most spread out subject: {most_spread_subject_idx}\n")

chemistry_idx = 2 
lowest_chem_student_idx = np.argmin(marks[:, chemistry_idx])
lowest_chem_student_total = student_totals[lowest_chem_student_idx]
print("Task 7:")
print(f"Total marks of student lowest in Chemistry (assuming index {chemistry_idx}): {lowest_chem_student_total}")

Task 1:
Average of each subject: [66.  64.2 69.8 71.2]
Total of each student: [308 228 328 282 210]

Task 2:
Index of toughest subject: 1

Task 3:
Index of overall topper: 2

Task 4:
Highest marks in each subject: [ 95  92  98 100]

Task 5:
Students scoring above 60 per subject: [3 3 3 3]

Task 6:
Index of most spread out subject: 0

Task 7:
Total marks of student lowest in Chemistry (assuming index 2): 282


Q9. The annual function draw
Tasks

Make the whole draw repeatable, then pick 3 winners from participants.
Generate the attendance percentages of these 10 participants as whole numbers between 60 and 100.
Generate a 4 × 3 table of random decimals between 0 and 1, then turn it into whole-number marks out of 100.
Shuffle the participant list and print the first four as the front-row seating.
Simulate 20 dice rolls and print how many times a 6 appeared.
From the attendance of task 2, print the roll numbers of the participants who crossed 80.


In [55]:
participants = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [56]:
np.random.seed(42)

winners = np.random.choice(participants, size=3)
print("Task 1:")
print(f"{winners}\n")


np.random.seed(42)

attendance = np.random.randint(60, 101, size=10)
print("Task 2:")
print(f"{attendance}\n")


np.random.seed(42)
decimals_table = np.random.rand(4, 3)

marks_table = (decimals_table * 100).astype(int)
print("Task 3:")
print(f"{marks_table}\n")

np.random.seed(42)

shuffled_participants = participants.copy()
np.random.shuffle(shuffled_participants)
front_row = shuffled_participants[:4]
print("Task 4:")
print(f"{front_row}\n")


np.random.seed(42)

dice_rolls = np.random.randint(1, 7, size=20)
sixes_count = np.sum(dice_rolls == 6)
print("Task 5:")
print(f"{sixes_count}\n")


crossed_80 = participants[attendance > 80]
print("Task 6:")
print(f"{crossed_80}")

Task 1:
[107 104 108]

Task 2:
[98 88 74 67 80 98 78 82 70 70]

Task 3:
[[37 95 73]
 [59 15 15]
 [ 5 86 60]
 [70  2 96]]

Task 4:
[109 102 106 101]

Task 5:
3

Task 6:
[101 102 106 108]



Q10. Grace marks and weightage
Tasks

Apply the subject-wise grace marks to the whole class, keeping every value at or below 100.
Multiply each subject by its own weightage and print the table rounded to 1 decimal.
Produce a table showing how far each mark sits from that subject's own class average.
Give 5 bonus marks to the first student, 0 to the second, 2 to the third and 0 to the fourth — in a single operation.
From the table of task 3, print how many entries lie below the subject average.
Produce a table where every subject is brought to one scale by subtracting its average and dividing by its spread. Round to 2 decimals.

In [57]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40]])

grace     = np.array([5, 0, 8, 3])
weightage = np.array([1.2, 1.0, 1.1, 1.0])

In [59]:
marks_with_grace = np.minimum(marks + grace, 100)
print("Task 1:")
print(f"{marks_with_grace}\n")

weighted_marks = np.round(marks * weightage, 1)
print("Task 2:")
print(f"{weighted_marks}\n")

subject_averages = np.mean(marks, axis=0)
distance_from_avg = marks - subject_averages
print("Task 3:")
print(f"{distance_from_avg}\n")

bonus = np.array([5, 0, 2, 0])

marks_with_bonus = marks + bonus.reshape(-1, 1)
print("Task 4:")
print(f"{marks_with_bonus}\n")

below_avg_count = np.sum(distance_from_avg < 0)
print("Task 5:")
print(f"{below_avg_count}\n")

subject_spread = np.std(marks, axis=0)
scaled_marks = np.round((marks - subject_averages) / subject_spread, 2)
print("Task 6:")
print(f"{scaled_marks}")

Task 1:
[[ 77  85  68  94]
 [ 50  30 100  58]
 [ 93  66  82 100]
 [100  92  63  43]]

Task 2:
[[ 86.4  85.   66.   91. ]
 [ 54.   30.  107.8  55. ]
 [105.6  66.   81.4 100. ]
 [114.   92.   60.5  40. ]]

Task 3:
[[ -3.    16.75 -11.75  19.5 ]
 [-30.   -38.25  26.25 -16.5 ]
 [ 13.    -2.25   2.25  28.5 ]
 [ 20.    23.75 -16.75 -31.5 ]]

Task 4:
[[ 77  90  65  96]
 [ 45  30  98  55]
 [ 90  68  76 102]
 [ 95  92  55  40]]

Task 5:
8

Task 6:
[[-0.16  0.7  -0.7   0.79]
 [-1.56 -1.59  1.57 -0.67]
 [ 0.68 -0.09  0.13  1.15]
 [ 1.04  0.99 -1.   -1.27]]
