In [1]:
import numpy as np

Q11. Distances and arrangements
Tasks

Build a 5 × 5 table of walking distances between every pair of hostel blocks, with all values positive.
For each block, print the distance to the block farthest from it.
Print the index of the block nearest to block 0, leaving out block 0 itself.
Print the two blocks that are closest to each other anywhere on the road.
Arrange roll numbers 1 to 24 into rows of 6 without typing the number of rows.
Turn sanskrit into a form that can be attached as a column to a mark sheet, using two different methods.
Turn sanskrit into a single-row table of shape (1, 5).

In [2]:
metres   = np.array([200, 500, 900, 100, 700])
sanskrit = np.array([65, 70, 88, 92, 54])

In [3]:
distances = np.abs(metres.reshape(-1, 1) - metres)
print("Task 1:")
print(f"{distances}\n")

farthest_distances = np.max(distances, axis=1)
print("Task 2:")
print(f"{farthest_distances}\n")

dist_from_0 = distances[0].astype(float)
dist_from_0[0] = np.inf
nearest_to_0 = np.argmin(dist_from_0)
print("Task 3:")
print(f"{nearest_to_0}\n")

dist_no_diag = distances.astype(float)
np.fill_diagonal(dist_no_diag, np.inf)
closest_pair = np.unravel_index(np.argmin(dist_no_diag), dist_no_diag.shape)
print("Task 4:")
print(f"Blocks {closest_pair[0]} and {closest_pair[1]}\n")

rolls = np.arange(1, 25).reshape(-1, 6)
print("Task 5:")
print(f"{rolls}\n")

method_1 = sanskrit.reshape(-1, 1)
method_2 = sanskrit[:, np.newaxis]
print("Task 6:")
print("Method 1 (reshape):\n", method_1)
print("Method 2 (newaxis):\n", method_2, "\n")

sanskrit_row = sanskrit.reshape(1, -1)
print("Task 7:")
print(f"{sanskrit_row}")

Task 1:
[[  0 300 700 100 500]
 [300   0 400 400 200]
 [700 400   0 800 200]
 [100 400 800   0 600]
 [500 200 200 600   0]]

Task 2:
[700 400 800 800 600]

Task 3:
3

Task 4:
Blocks 0 and 3

Task 5:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Task 6:
Method 1 (reshape):
 [[65]
 [70]
 [88]
 [92]
 [54]]
Method 2 (newaxis):
 [[65]
 [70]
 [88]
 [92]
 [54]] 

Task 7:
[[65 70 88 92 54]]


Q12. The master mark sheet
Tasks

Produce a flat one-line version of the master that can be edited without affecting the master. Change its first value to 999 and print the master.
Produce a flat version that shares memory with the master. Change its last value to 111 and print the master.
Set the entire middle row to 0 while leaving the master unchanged.
Double the first two columns without changing the master.
Double the first two columns, this time changing the master itself.
Produce a copy of the master in which every value above 50 is reduced by 10, leaving the master untouched.


In [4]:
master = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

In [ ]:
flat_copy = master.flatten()
flat_copy[0] = 999
print("Task 1:")
print(f"{master}\n")

flat_view = master.ravel()
flat_view[-1] = 111
print("Task 2:")
print(f"{master}\n")

master = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

master_task3 = master.copy()
master_task3[1, :] = 0
print("Task 3:")
print(f"{master_task3}\n")

master_task4 = master.copy()
master_task4[:, :2] *= 2
print("Task 4:")
print(f"{master_task4}\n")

master[:, :2] *= 2
print("Task 5:")
print(f"{master}\n")

master_task6 = master.copy()
master_task6[master_task6 > 50] -= 10
print("Task 6:")
print(f"{master_task6}")

Q13. Merging section records
Tasks

Combine Section A and Section B into one mark sheet and print its shape.
Attach a totals column to that combined mark sheet.
Build a two-column table from roll_C and marks_C, roll numbers first.
Add a new student — roll 205, marks 73 — as a fresh row to the table of task 3.
Attach a serial-number column, starting from 1, to the left of the combined mark sheet of task 1.
From the combined sheet, produce a new sheet holding only the students whose total crosses 200.
Attach a grade column to the combined sheet: 225 and above → A, 150 to 224 → B, below 150 → C.

In [5]:
sec_A = np.array([[72, 85, 60],
                  [45, 30, 98],
                  [88, 66, 74]])

sec_B = np.array([[95, 92, 55],
                  [30, 48, 62]])

roll_C  = np.array([201, 202, 203, 204])
marks_C = np.array([67, 82, 45, 91])

In [ ]:
combined_sec = np.vstack((sec_A, sec_B))
print("Task 1:")
print(f"Shape of combined mark sheet: {combined_sec.shape}\n")

totals = np.sum(combined_sec, axis=1).reshape(-1, 1)
combined_with_totals = np.hstack((combined_sec, totals))
print("Task 2:")
print(f"{combined_with_totals}\n")

table_C = np.column_stack((roll_C, marks_C))
print("Task 3:")
print(f"{table_C}\n")

new_student = np.array([[205, 73]])
table_C_updated = np.vstack((table_C, new_student))
print("Task 4:")
print(f"{table_C_updated}\n")

serial_nums = np.arange(1, combined_sec.shape[0] + 1).reshape(-1, 1)
combined_with_serial = np.hstack((serial_nums, combined_sec))
print("Task 5:")
print(f"{combined_with_serial}\n")

high_scorers = combined_sec[totals.flatten() > 200]
print("Task 6:")
print(f"{high_scorers}\n")

conditions = [
    totals.flatten() >= 225,
    (totals.flatten() >= 150) & (totals.flatten() < 225),
    totals.flatten() < 150
]
choices = ['A', 'B', 'C']
grades = np.select(conditions, choices).reshape(-1, 1)

combined_with_grades = np.hstack((combined_sec.astype(str), grades))
print("Task 7:")
print(f"{combined_with_grades}")

Q14. Cleaning and grading
Tasks

Repair the attendance row: every value above 100 becomes 100, and every -1 becomes the average of the genuine entries.
Label each repaired value: 85 and above → Regular, 60 to 84 → Average, below 60 → Short.
Print the index positions of the Short students along with their attendance values.
In the marks table, find the row and column position of every mark below 50.
Print the actual marks sitting at those positions.
Replace every mark below 35 with 35, and print how many entries were changed.
Print the index of the student who has the highest number of marks below 60.

In [7]:
marks = np.array([[70, 65, 80],
                  [55, 90, 32],
                  [88, 76, 91],
                  [40, 52, 45],
                  [60, 58, 66]])

attendance = np.array([88, -1, 105, 76, 45, -1, 92, 120, 67, 30])

In [8]:
attendance[attendance > 100] = 100
genuine_mask = attendance != -1
average_genuine = np.mean(attendance[genuine_mask])
attendance[attendance == -1] = average_genuine
print(attendance)

labels = np.empty(attendance.shape, dtype=object)
labels[attendance >= 85] = 'Regular'
labels[(attendance >= 60) & (attendance < 85)] = 'Average'
labels[attendance < 60] = 'Short'

short_indices = np.where(labels == 'Short')[0]
short_values = attendance[short_indices]
print("Indices of 'Short' students:", short_indices)
print("Their attendance values:", short_values)

rows, cols = np.where(marks < 50)
print(f"rows: {rows}")
print(f"cols: {cols}")

actual_marks = marks[rows, cols]
print(actual_marks)

below_35_mask = marks < 35
changed_count = np.sum(below_35_mask)
marks[below_35_mask] = 35
print(f"Entries changed: {changed_count}")

marks_below_60_counts = np.sum(marks < 60, axis=1)
worst_student_index = np.argmax(marks_below_60_counts)
print(worst_student_index)

[ 88  74 100  76  45  74  92 100  67  30]
Indices of 'Short' students: [4 9]
Their attendance values: [45 30]
rows: [1 3 3]
cols: [2 0 2]
[32 40 45]
Entries changed: 1
3


Q15. The final weighted result
Tasks

Compute the weighted final score of every student using w.
Print the index of the student with the highest weighted score.
Using a multiplication rather than sum, produce the subject-wise total marks of the whole class.
The board has proposed two weightage schemes, held in W. Compute both final scores of all four students in one multiplication.
From that result, print how many students score higher under the second scheme.
Print the difference between the two schemes for every student, rounded to 2 decimals.
Attach the better of the two scores as a fourth column to M.

In [9]:
M = np.array([[70, 65, 80],
              [55, 90, 72],
              [88, 76, 91],
              [60, 58, 66]])

w = np.array([0.3, 0.3, 0.4])

W = np.array([[0.3, 0.5],
              [0.3, 0.2],
              [0.4, 0.3]])

In [10]:
weighted_scores = M @ w
print(weighted_scores)

highest_student_index = np.argmax(weighted_scores)
print(highest_student_index)

subject_totals = np.ones(M.shape[0]) @ M
print(subject_totals)

scores_W = M @ W
print(scores_W)

higher_in_second = np.sum(scores_W[:, 1] > scores_W[:, 0])
print(higher_in_second)

differences = np.round(scores_W[:, 1] - scores_W[:, 0], 2)
print(differences)

better_scores = np.max(scores_W, axis=1)
M_updated = np.column_stack((M, better_scores))
print(M_updated)

[72.5 72.3 85.6 61.8]
2
[273. 289. 309.]
[[72.5 72. ]
 [72.3 67.1]
 [85.6 86.5]
 [61.8 61.4]]
1
[-0.5 -5.2  0.9 -0.4]
[[70.  65.  80.  72.5]
 [55.  90.  72.  72.3]
 [88.  76.  91.  86.5]
 [60.  58.  66.  61.8]]
