In [2]:
import numpy as np

Q1. Three students' marks arrived as three separate lists, and one old record arrived as text.

Tasks

Build one table from s1, s2 and s3.
From that table, print the number of students and the number of subjects as two separate numbers.
Print the total count of marks entries stored in the table.
Store the same table as decimals instead of whole numbers.
Convert old into a form where arithmetic works, then print the total marks of both students.
Attach old below the main table so that all five students sit in one table.

In [8]:
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]
old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

arr=np.arange(1,7).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:

table=np.array([s1,s2,s3])
print(table)

tableShape=table.shape
print("no of student", tableShape[0])
print("no of subjects", tableShape[1])

print("total count", table.size)

tableFloat=table.astype("float32")
print(tableFloat)

oldForm=old.astype("int32")
print(oldForm)

finalTable=np.vstack((table,oldForm))
print(finalTable)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
no of student 3
no of subjects 4
total count 12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[[62 71 55 80]
 [49 58 66 73]]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


Q2. Templates and sequences
Tasks

Create a blank mark sheet for 6 students and 4 subjects, every entry starting at 0.
Create a table of the same size where every student is temporarily given 35.
A batch has roll numbers running from 101 to 130. Generate only the alternate roll numbers, and print how many were generated.
Split a 3-hour practical into 7 equally spaced time markers, including both the start and the end.
Create a 5 × 5 table that has 10 on the diagonal and 0 everywhere else.
Create a 4 × 4 table that has 100 on the diagonal and 35 everywhere else.

In [12]:
markSheet=np.zeros((6,4),dtype="int32")
print(markSheet)

tempSheet=np.full((6,4),35)
print(tempSheet)

rollNo=np.arange(101,131,2)
print(rollNo)

examTime=np.linspace(0,3,7)
print(examTime)

diaData=np.eye(5,dtype="int32")*10
print(diaData)

a=np.eye(4,dtype="int32")*65
b=np.full((4,4),35)

ans=a+b
print(ans)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


Q3. The attendance row
Tasks

Print the first and the last student's attendance without writing the class strength anywhere in your code.
Print the attendance of every alternate student, starting from the second one.
Print the last four values.
Reverse the row, then print every third value of the reversed row.
Change the attendance of the two middle students to 30 each.
Compare the first half of the row with the second half position by position, and print the difference.
Print the top three values of the row after reversing it.


In [ ]:
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

print("1st roll", present[0])
print("last roll", present[-1])

attendence=present[1::2]
print(attendence)

last4=present[-1:-5:-1]
print(last4)

rev=present[::-1]
print(rev[::3])

mid=len(present)//2
present[mid-1:mid+1]=30
print(present)

firstHalf=present[:mid]
secondHalf=present[mid:]
diff=secondHalf-firstHalf
print(diff)

print(rev[:3])



1st roll 22
last roll 23
[18 12 24 21 23]
[23 17 21  9]
[23  9 12 22]
[22 18 25 12 30 30  9 21 17 23]
1st [22 18 25 12 30]
2nd [30  9 21 17 23]
[ 8 -9 -4  5 -7]
[23 17 21]


Q4. Reading the mark sheet
The columns are Math, Physics, Chemistry and English.

Tasks

Print the Physics and Chemistry marks of the middle three students only.
Print the last subject's marks for the whole class.
Produce a table containing only the first and the last subject of every student.
Print the mark sheet with the students in reverse order.
Increase only the Chemistry marks of the whole class by 5, leaving the rest unchanged.
Print the mark that sits in the last row and the second-last column.
Produce a table of the last two students and their first two subjects.


In [20]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])


In [25]:
midStud=marks[1:4,1:3]
print(midStud)

lastSub=marks[:,-1]
print(lastSub)

table=marks[:,0::3]
print(table)

revMark=marks[::-1,::-1]
print(revMark)

marks[:,2]+=5
print(marks)

stud=marks[-1,-2]
print(stud)

mat=marks[-1:-3:-1,0:2]
print(mat)

[[30 98]
 [66 74]
 [92 55]]
[ 91  55 100  40  70]
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
[[ 70  62  48  30]
 [ 40  55  92  95]
 [100  74  66  88]
 [ 55  98  30  45]
 [ 91  60  85  72]]
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]
67
[[30 48]
 [95 92]]


Q5. Scholarship shortlisting
Tasks

Print the totals of students who scored above 250.
Print the totals of students scoring above 180 but below 250.
Print the totals of students who scored either below 150 or above 380.
Print how many students fall in the band of task 2.
Print the average of only those students who scored above 200.
Print the index position of every student below 150.
Print the highest total among the students who did not make the merit band of task1

In [26]:
totals = np.array([245, 310, 178, 392, 140, 265, 199, 155, 288, 132])

In [33]:
student1=totals[totals>250]
print(student1)

student2=totals[(totals>180) & (totals<250)]
print(student2)

student3=totals[(totals<150) | (totals>380)]
print(student3)

print(len(student2))

student4=totals[totals>200];
print(np.mean(student4))

student5=np.where(totals<150)
print(student5[0])

student6=totals[totals<=250]
print(np.max(student6))


[310 392 265 288]
[245 199]
[392 140 132]
2
300.0
[4 9]
245


Q6. After revaluation
Tasks

Increase every student's marks by 15% and round to 2 decimals.
After the increase, no student may show more than 100. Produce the corrected list.
Print how many students gained less than 10 marks from this increase.
The pass mark is 40. Print how many students were failing before the increase and how many after.
Print each student's marks as a percentage of the topper's marks, rounded to 1 decimal.
Print the total number of marks the school gave away in this revaluation.

In [34]:
marks = np.array([40, 55, 62, 88, 95, 33, 71, 58])

In [40]:
newMarks=np.round(marks*1.15,2)
print(newMarks)

limitMarks= np.clip(newMarks, a_min=None, a_max=100)
print(limitMarks)

arr=limitMarks-marks
student1=arr[arr<10]
print(len(student1))

arr1=marks[marks<40]
print(len(arr1))

topperMark=np.max(marks)
stud=np.round((marks/topperMark)*100,1)
print(stud)

print(np.sum(arr))


[ 46.    63.25  71.3  101.2  109.25  37.95  81.65  66.7 ]
[ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]
6
1
[ 42.1  57.9  65.3  92.6 100.   34.7  74.7  61.1]
64.85000000000001


Q7. The result summary
Tasks

Print the class average and the middle value of the class.
Print the gap between the highest and the lowest marks.
Print the index positions of the topper and of the weakest student.
Print the second highest marks in the class.
Print how many students scored above the class average.
Print how many students lie within one standard deviation of the class average.
Print the class average after removing the topper.

In [49]:
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])

In [51]:
avg=np.mean(marks)
median=np.median(marks)
print(avg,median)

maxMark=np.max(marks)
minMark=np.min(marks)
print(maxMark-minMark)

topperPos=np.where(marks==maxMark)
print(topperPos[0][0])
weakPos=np.where(marks==minMark)
print(weakPos[0][0])

secondHigh=np.sort(marks)[-2]
print(secondHigh)

student1=marks[marks>avg]
print(len(student1))

std=np.std(marks)
lower=avg-std
high=avg+std
student2=marks[(marks>=lower) & (marks<=high)]
print(len(student2))


student3=marks[marks!=maxMark]
print(np.round(np.mean(student3),2))

65.9 69.5
65
3
4
91
6
5
62.67


Q8. Subject-wise and student-wise reports
Tasks

Print the average of each subject and the total of each student.
Print the index of the toughest subject for the class.
Print the index of the student who topped overall.
For every subject, print the marks of the student who topped that subject.
Print how many students scored above 60 in each subject.
Print the index of the subject in which the class marks are the most spread out.
Print the total marks of the student who scored the lowest in Chemistry.

In [3]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])

In [26]:
subjectAvg=np.mean(marks,axis=0)
studentTotal=np.sum(marks, axis=1)
print("Subject Average:",subjectAvg)
print("Student Total:",studentTotal)

idxTough=np.argmin(subjectAvg)
print("Index of toughest Subject:",idxTough);

topperIdx=np.argmax(studentTotal)
print("Index of topper", topperIdx)

topperIdxSub=np.max(marks,axis=0)
print("Topper marksof subject",topperIdxSub)

above60=np.sum(marks>60, axis=0)
print("Count of students above 60:",above60)

std=np.std(marks,axis=0)
spreadOutIndex=np.argmax(std)
print("Index of subject where data is most spread data: ",spreadOutIndex)

lowestChem=2
idxLowest=np.argmin(marks[:,lowestChem])
print("Total student who scored lowest in Chemistry:", studentTotal[idxLowest])


Subject Average: [66.  64.2 69.8 71.2]
Student Total: [308 228 328 282 210]
Index of toughest Subject: 1
Index of topper 2
Topper marksof subject [ 95  92  98 100]
Count of students above 60: [3 3 3 3]
Index of subject where data is most spread data:  0
Total student who scored lowest in Chemistry: 282


Q9. The annual function draw
Tasks

Make the whole draw repeatable, then pick 3 winners from participants.
Generate the attendance percentages of these 10 participants as whole numbers between 60 and 100.
Generate a 4 × 3 table of random decimals between 0 and 1, then turn it into whole-number marks out of 100.
Shuffle the participant list and print the first four as the front-row seating.
Simulate 20 dice rolls and print how many times a 6 appeared.
From the attendance of task 2, print the roll numbers of the participants who crossed 80.


In [9]:
participants = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
np.random.seed(42)
randomParticipate=np.random.choice(participants, 3, replace=False)
print(randomParticipate)

randamAttendance=np.random.randint(60,101, size=10)
print("attendance percentages:",randamAttendance)

np.random.seed(42)
randomNum=np.random.rand(4,3)
finalMark=(randomNum*100).astype("int32")
print("random marks:",finalMark)

participantsCopy=participants.copy()
np.random.shuffle(participantsCopy)
print("1st 4 elements in shuffle:", participantsCopy[0:4])

diceRoll=np.random.randint(1,7,size=20)
freq6=np.sum(diceRoll==6)
print("dice roll:",diceRoll)
print("Freq of 6 in it:",freq6)

attendence80=np.where(randamAttendance>80)[0]
rollNo=participants[attendence80]
print("Roll No with attendance above 80:",rollNo)


[109 102 106]
attendance percentages: [78 82 70 70 83 95 99 83 62 81]
random marks: [[37 95 73]
 [59 15 15]
 [ 5 86 60]
 [70  2 96]]
1st 4 elements in shuffle: [110 103 109 107]
dice roll: [5 4 1 1 3 3 2 4 4 6 6 6 3 4 4 1 3 5 3 5]
Freq of 6 in it: 3
Roll No with attendance above 80 [102 105 106 107 108 110]



Q10. Grace marks and weightage
Tasks

Apply the subject-wise grace marks to the whole class, keeping every value at or below 100.
Multiply each subject by its own weightage and print the table rounded to 1 decimal.
Produce a table showing how far each mark sits from that subject's own class average.
Give 5 bonus marks to the first student, 0 to the second, 2 to the third and 0 to the fourth — in a single operation.
From the table of task 3, print how many entries lie below the subject average.
Produce a table where every subject is brought to one scale by subtracting its average and dividing by its spread. Round to 2 decimals.

In [ ]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40]])

grace     = np.array([5, 0, 8, 3])
weightage = np.array([1.2, 1.0, 1.1, 1.0])

In [23]:
temp=marks+grace
newMarks=np.clip(temp, a_min=None, a_max=100)
print(newMarks)

temp2=marks*weightage
updateMarks=np.round(temp2, 1)
print(updateMarks)

classAvg=marks.mean(axis=0)
devMarks=marks-classAvg
print("The deviation from own class avg marks:\n",devMarks)

bonus=np.array([5,0,2,0]).reshape(-1,1)
markWithBonus=marks+bonus
print("The marks with bonus:",markWithBonus)

countBelowAvg=np.sum(devMarks<0)
print("The cound of students got below subject average:",countBelowAvg)

marksStd=marks.std(axis=0)
scaleMarks=np.round((marks-classAvg)/marksStd,2)
print("The scaled marks:",scaleMarks)


[[ 77  85  68  94]
 [ 50  30 100  58]
 [ 93  66  82 100]
 [100  92  63  43]]
[[ 86.4  85.   66.   91. ]
 [ 54.   30.  107.8  55. ]
 [105.6  66.   81.4 100. ]
 [114.   92.   60.5  40. ]]
The deviation from own class avg marks:
 [[ -3.    16.75 -11.75  19.5 ]
 [-30.   -38.25  26.25 -16.5 ]
 [ 13.    -2.25   2.25  28.5 ]
 [ 20.    23.75 -16.75 -31.5 ]]
The marks with bonus: [[ 77  90  65  96]
 [ 45  30  98  55]
 [ 90  68  76 102]
 [ 95  92  55  40]]
The cound of students got below subject average: 8
The scaled marks: [[-0.16  0.7  -0.7   0.79]
 [-1.56 -1.59  1.57 -0.67]
 [ 0.68 -0.09  0.13  1.15]
 [ 1.04  0.99 -1.   -1.27]]


Q11. Distances and arrangements
Tasks

Build a 5 × 5 table of walking distances between every pair of hostel blocks, with all values positive.
For each block, print the distance to the block farthest from it.
Print the index of the block nearest to block 0, leaving out block 0 itself.
Print the two blocks that are closest to each other anywhere on the road.
Arrange roll numbers 1 to 24 into rows of 6 without typing the number of rows.
Turn sanskrit into a form that can be attached as a column to a mark sheet, using two different methods.
Turn sanskrit into a single-row table of shape (1, 5).

In [2]:
metres   = np.array([200, 500, 900, 100, 700])
sanskrit = np.array([65, 70, 88, 92, 54])

In [18]:
arr=metres.reshape(-1,1)
distances=np.abs(metres-arr)
print("The distances:",distances)

maxDistance=distances.max(axis=1)
print("The farthest distances:",maxDistance)

dist=distances[0]
dist=dist[1:]
lowestIdx=np.argmin(dist)
print("The index of block nearest to 0:",lowestIdx+1)

d=np.where(distances==0, np.inf, distances)
blocks=np.argmin(d)
cols=d.shape[1]

row=blocks//cols
col=blocks%cols
print("Index of smallest:", row, col)

rolls=np.arange(1,25).reshape(-1,4)
print("Roll Numbers arrange:",rolls)

colSanskrit=sanskrit.reshape(-1,1)
print("Column array of sanskrit:",colSanskrit)

rowSanskrit=sanskrit.reshape(1,-1)
print("Row matrix of sanskrit:",rowSanskrit)

The distances: [[  0 300 700 100 500]
 [300   0 400 400 200]
 [700 400   0 800 200]
 [100 400 800   0 600]
 [500 200 200 600   0]]
The farthest distances: [700 400 800 800 600]
The index of block nearest to 0: 3
Index of smallest: 0 3
Roll Numbers arrange: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Column array of sanskrit: [[65]
 [70]
 [88]
 [92]
 [54]]
Row matrix of sanskrit: [[65 70 88 92 54]]


Q12. The master mark sheet
Tasks

Produce a flat one-line version of the master that can be edited without affecting the master. Change its first value to 999 and print the master.

Produce a flat version that shares memory with the master. Change its last value to 111 and print the master.
Set the entire middle row to 0 while leaving the master unchanged.

Double the first two columns without changing the master.

Double the first two columns, this time changing the master itself.

Produce a copy of the master in which every value above 50 is reduced by 10, leaving the master untouched.

In [3]:
master = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

In [ ]:
master1D=master.flatten()
master1D[0]=999
print("Changed master:",master1D)

master1Dview=master.ravel()
master1Dview[-1]=111
print("Changed master with same view:",master1Dview)

masterCopy=master.copy()
row=masterCopy.shape[0]
masterCopy[row//2,:]=[0]
print("Edited middle row:",masterCopy)

doubleMatrix=np.array([2,2,1]).reshape(1,-1)
masterCopyDouble=master.copy()
masterDouble=masterCopyDouble*doubleMatrix
print("Double without changing master matrix:",masterDouble)

master=master*doubleMatrix
print("Double changing master matrix:",master)

masterOp=master.copy()
masterOp=np.where(masterOp>50, masterOp-10, masterOp)
print("Operation above 50:", masterOp)

Changed master: [999  80  30 160 200  60 280 320 111]
Changed master with same view: [ 40  80  30 160 200  60 280 320 111]
Edited middle row: [[ 40  80  30]
 [  0   0   0]
 [280 320 111]]
Double without changing master matrix: [[ 80 160  30]
 [320 400  60]
 [560 640 111]]
Double changing master matrix: [[ 80 160  30]
 [320 400  60]
 [560 640 111]]
Operation above 50: [[ 70 150  30]
 [310 390  50]
 [550 630 101]]
[[ 80 160  30]
 [320 400  60]
 [560 640 111]]


Q13. Merging section records
Tasks

Combine Section A and Section B into one mark sheet and print its shape.
Attach a totals column to that combined mark sheet.
Build a two-column table from roll_C and marks_C, roll numbers first.
Add a new student — roll 205, marks 73 — as a fresh row to the table of task 3.
Attach a serial-number column, starting from 1, to the left of the combined mark sheet of task 1.
From the combined sheet, produce a new sheet holding only the students whose total crosses 200.
Attach a grade column to the combined sheet: 225 and above → A, 150 to 224 → B, below 150 → C.

In [3]:
sec_A = np.array([[72, 85, 60],
                  [45, 30, 98],
                  [88, 66, 74]])

sec_B = np.array([[95, 92, 55],
                  [30, 48, 62]])

roll_C  = np.array([201, 202, 203, 204])
marks_C = np.array([67, 82, 45, 91])

In [19]:
combinedMarks=np.vstack((sec_A,sec_B))
print("Shape of combined marksheet:",combinedMarks.shape)

marksTotal=combinedMarks.sum(axis=1)
marksTotal=marksTotal.reshape(-1,1)
markSheet=np.hstack((combinedMarks,marksTotal))
print("Added total column:",markSheet)

roll_C=roll_C.reshape(-1,1)
marks_C=marks_C.reshape(-1,1)
rollMarks=np.hstack((roll_C,marks_C));
print("Roll + Marks:",rollMarks)

newEntry=np.array([205,73])
rollMarks=np.vstack((rollMarks,newEntry))
print("New Entry updated:",rollMarks)

limit=len(combinedMarks)
serialNo=np.arange(1,limit+1).reshape(-1,1)
serialComboMarks=np.hstack((serialNo,combinedMarks))
print("Serial Number updated:",serialComboMarks)


filterIndex=np.where(marksTotal>200)[0]
filterStudent=combinedMarks[filterIndex]
print("Filter Student above 200:",filterStudent)

grade=np.where(marksTotal>=225, "A", 
      np.where((marksTotal>=150) & (marksTotal<=224), "B", "C"))
grade=grade.reshape(-1,1)
marksWithGrade=np.hstack((combinedMarks,grade))
print("Marks with Grade:",marksWithGrade)

Shape of combined marksheet: (5, 3)
Added total column: [[ 72  85  60 217]
 [ 45  30  98 173]
 [ 88  66  74 228]
 [ 95  92  55 242]
 [ 30  48  62 140]]
Roll + Marks: [[201  67]
 [202  82]
 [203  45]
 [204  91]]
New Entry updated: [[201  67]
 [202  82]
 [203  45]
 [204  91]
 [205  73]]
Serial Number updated: [[ 1 72 85 60]
 [ 2 45 30 98]
 [ 3 88 66 74]
 [ 4 95 92 55]
 [ 5 30 48 62]]
Filter Student above 200: [[72 85 60]
 [88 66 74]
 [95 92 55]]
Marks with Grade: [['72' '85' '60' 'B']
 ['45' '30' '98' 'B']
 ['88' '66' '74' 'A']
 ['95' '92' '55' 'A']
 ['30' '48' '62' 'C']]


Q14. Cleaning and grading
Tasks

Repair the attendance row: every value above 100 becomes 100, and every -1 becomes the average of the genuine entries.
Label each repaired value: 85 and above → Regular, 60 to 84 → Average, below 60 → Short.
Print the index positions of the Short students along with their attendance values.
In the marks table, find the row and column position of every mark below 50.
Print the actual marks sitting at those positions.
Replace every mark below 35 with 35, and print how many entries were changed.
Print the index of the student who has the highest number of marks below 60.

In [22]:
marks = np.array([[70, 65, 80],
                  [55, 90, 32],
                  [88, 76, 91],
                  [40, 52, 45],
                  [60, 58, 66]])

attendance = np.array([88, -1, 105, 76, 45, -1, 92, 120, 67, 30])

In [30]:
attendance=np.where(attendance>100, 100, attendance)
genuine=attendance[attendance!=-1]
avg=genuine.mean()
attendance=np.where(attendance==-1, avg, attendance)
print("Rectified attendance:",attendance)

label=np.where(attendance>=85, "Regular",
      np.where((attendance>=60) & (attendance<=84), "Average", "Short"))

shortIndex=np.where(label=="Short")[0]
shortAttendance=attendance[shortIndex]
print("Indexes of short students:",shortIndex)
print("The attendance values:",shortAttendance)

rows,cols=np.where(marks<50)
print("Rows: ",rows)
print("Cols", cols)

actualMarks=marks[rows, cols]
print("Actual marks below 50:",actualMarks)

replaceReq=np.sum(marks<35)
print("Number of replacement required:",replaceReq)
marks=np.where(marks<35, 35, marks)
print("Replaced marks:",marks)

marksBelow60=np.sum(marks<60, axis=1)
marksIndex=np.argmax(marksBelow60)
print("Student with highest number of marks below 60:",marksIndex)

Rectified attendance: [ 88.    74.75 100.    76.    45.    74.75  92.   100.    67.    30.  ]
Indexes of short students: [4 9]
The attendance values: [45. 30.]
Rows:  [1 3 3]
Cols [2 0 2]
Actual marks below 50: [35 40 45]
Number of replacement required: 0
Replaced marks: [[70 65 80]
 [55 90 35]
 [88 76 91]
 [40 52 45]
 [60 58 66]]
Student with highest number of marks below 60: 3


Q15. The final weighted result
Tasks

Compute the weighted final score of every student using w.
Print the index of the student with the highest weighted score.
Using a multiplication rather than sum, produce the subject-wise total marks of the whole class.
The board has proposed two weightage schemes, held in W. Compute both final scores of all four students in one multiplication.
From that result, print how many students score higher under the second scheme.
Print the difference between the two schemes for every student, rounded to 2 decimals.
Attach the better of the two scores as a fourth column to M.

In [32]:
M = np.array([[70, 65, 80],
              [55, 90, 72],
              [88, 76, 91],
              [60, 58, 66]])

w = np.array([0.3, 0.3, 0.4])

W = np.array([[0.3, 0.5],
              [0.3, 0.2],
              [0.4, 0.3]])

In [40]:
weightedScore=M@w
print("Final weighted score:",weightedScore)

highestIndex=np.argmax(weightedScore)
print("The index of student with highest weighted score: ",highestIndex)

fact=np.ones(M.shape[0])
totalScores=fact@M
print("Total scores:",totalScores)

scores=M@W
print("Scores:",scores)

highInSec=np.sum(scores[:,0]<scores[:,1])
print("Higher in second scheme:",highInSec)

difference=np.round((scores[:,1]-scores[:,0]),2)
print("Difference b/w schemes:",difference)

betterScores=np.max(scores, axis=1).reshape(-1,1)
updatedM=np.hstack((M,betterScores))
print("Updated M:",updatedM)



Final weighted score: [72.5 72.3 85.6 61.8]
The index of student with highest weighted score:  2
Total scores: [273. 289. 309.]
Scores: [[72.5 72. ]
 [72.3 67.1]
 [85.6 86.5]
 [61.8 61.4]]
Higher in second scheme: 1
Difference b/w schemes: [-0.5 -5.2  0.9 -0.4]
Updated M: [[70.  65.  80.  72.5]
 [55.  90.  72.  72.3]
 [88.  76.  91.  86.5]
 [60.  58.  66.  61.8]]
