In [1]:
import numpy as np

Q1. Create an array of the first 12 odd numbers using a single np.arange call.

In [2]:
arr=np.arange(1,24,2);
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


Q2. Using np.linspace, create 9 equally spaced values from 5 to 45. Before running, predict the gap
between consecutive values - then verify.

In [3]:
arr=np.linspace(5,45,9)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


Q3. Create np.arange(1, 10) and np.linspace(1, 9, 9). Print both and compare their dtype. Why are
they different?

In [ ]:
arr1=np.arange(1,10)
arr2=np.linspace(1,9,9)

print(arr1) #give dtype as int64 => does not divides but prints a sequence
print(arr2) #give dtype as float64 => divides the given range into equal halves.

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


Q4. Create a 6x6 identity matrix with integer dtype - the output must show no decimal points.

In [5]:
arr=np.eye((6),dtype="int32")
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


Q5. Create a 3x4 matrix where every element is 5, and report its shape, size, and ndim

In [6]:
arr=np.full((3,4), 5);

print("shape", arr.shape)
print("size", arr.size)
print("no of dimensions", arr.ndim)

shape (3, 4)
size 12
no of dimensions 2


Q6. Given a = np.array([2, 4, 6]) and b = np.array([2.0, 4.0, 6.0]) - check both dtypes, then convert b
to int with astype and verify the dtypes now match.

In [7]:
a=np.array([2,4,6])
b=np.array([2.0, 4.0, 6.0])

print(a.dtype)
print(b.dtype)

b=b.astype("int32")
print(a.dtype)
print(b.dtype)

int64
float64
int64
int32


Q7. Predict the exact output of np.array([10.9, 25.5, 39.99]).astype(int) before running it. What rule
does the result prove?

In [8]:
#concept => making it to floor to convert to int from float
arr=np.array([10.9, 25.5, 39.99]).astype(int)
print(arr)

[10 25 39]


Q8. Q8. Given arr = np.arange(10, 101, 10) - extract: (a) the 4th element, (b) the last element using
negative indexing, (c) the 2nd-last element.

In [9]:
arr = np.arange(10, 101, 10)
print(arr[3])
print(arr[-1])
print(arr[-2])

40
100
90


Q9. From the same arr, slice out exactly [30 40 50 60], and separately produce the full array in
reverse

In [10]:
arr = np.arange(10, 101, 10)
arrSlice=arr[2:6]

ans=arrSlice[::-1]
print(ans)

[60 50 40 30]


Q10. Given arr = np.arange(1, 21) - extract every 3rd element starting from index 1 (result: 2, 5, 8,
...).

In [11]:
arr = np.arange(1, 21)
ans=arr[1::3]
print(ans)

[ 2  5  8 11 14 17 20]


Q11. Using one slice only, extract everything from arr (1-20) EXCEPT the first two and the last two
elements.

In [13]:
arr=np.arange(1,21)
n=len(arr)
ans=arr[2:len(arr)-2]
print(ans)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


Q12. Using the matrix below, extract: (a) the 3rd row, (b) the last column, (c) the centre 3x3 block.

m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

In [14]:
m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

a1=m[2,:]
a2=m[:,-1]
a3=m[1:4, 1:4]

print(a1)
print(a2)
print(a3)

[11 12 13 14 15]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Q13. From the same matrix, extract the four corner elements as a 2x2 array - using step slicing
only.

In [15]:
m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

ans=m[0::4,0::4]
print(ans)

[[ 1  5]
 [21 25]]


Q14. From the same matrix, extract every alternate row AND every alternate column at the same
time (the result is 3x3).

In [18]:
m = np.array([[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

ans1=m[0::2,0::2]
print(ans1)

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


Q15. Given the marks array below - (a) extract all marks greater than 60; (b) extract marks between
50 and 80 using two conditions with & (remember the parentheses!).

marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

In [19]:
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
ans1=marks[marks>60]
ans2=marks[(marks>=50)&(marks<=80)]

print(ans1)
print(ans2)

[91 77 62 85 70]
[56 77 62 70]
