In [1]:
import numpy as np

Q1.
A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

In [3]:
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])
bonus=np.array([5,2,8]).reshape(1,-1)

updatedMarks=marks+bonus
countCap=np.where(updatedMarks>100)[0]
updatedMarks=np.where(updatedMarks>100, 100, updatedMarks)
print("Marks after bonus:",updatedMarks)
print("Count of marks that was capped:",countCap)


Marks after bonus: [[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Count of marks that was capped: [0 1 2 2]


Q2.
Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

In [6]:
arr=np.ones((5,5),dtype="int32")
arr[1:4,1:4]=0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Q3.
Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4, -1) fails.

In [ ]:
arr=np.arange(30).reshape(5,-1).T
arrShape=arr.shape # 6 5
print("The shape:",arrShape)

#np.arange(30).reshape(4, -1) fails as 30/4 is not a whole number hence 
#valid whole number cannot be placed in place of -1 => error

The shape: (6, 5)


Q4.
Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

In [ ]:
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])
joinedArray=np.hstack((heights,weights))
print("Shape:",joinedArray.shape)

heights=heights.reshape(-1,1)
weights=weights.reshape(-1,1)
mergedArray=np.hstack((heights,weights))
print("Shape:",mergedArray.shape)
print("Right merge:",mergedArray)

#for hstack, array merge side by side hence we need to reshape and then do hstack

Shape: (8,)
Shape: (4, 2)
Right merge: [[172  68]
 [158  52]
 [181  84]
 [166  59]]


Q5.
Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

In [14]:
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])
sales=sales.reshape(4,3)
avg=np.mean(sales,axis=1)
highIndex=np.argmax(avg)

print("Highest avg:",avg[highIndex],"Index: ",highIndex)


Highest avg: 212.66666666666666 Index:  3


Q6.
Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use np.outer — reshape one of the operands so that broadcasting produces the grid.

a = np.array([2, 3, 4])

In [15]:
a = np.array([2, 3, 4])
a=a.reshape(1,-1)

Q7.
Create an array of numbers from 1 to 20 and replace every multiple of 3 with -1.

In [16]:
arr=np.arange(1,21)
arr=np.where(arr%3==0, -1, arr)
print("Updated array:",arr)

Updated array: [ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


Q8.
For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization (x - col_min) / (col_max - col_min). Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

In [32]:
X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

col_min=X.min(axis=0)
col_max=X.max(axis=0)

arr=(X-col_min)/(col_max-col_min)
print(arr)

[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]


Q9.
Award medals to the scores below using nested np.where: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

In [36]:
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
medals=np.where(scores>=90, "Gold", 
        np.where(scores>=75, "Silver",
        np.where(scores>=60, "Bronze", "None")))

print("Medals: ",medals)

gold=np.sum(medals=="Gold")
print("No of gold medals",gold)

silver=len(np.where(medals=="Silver")[0])
print("No of silver medals",silver)

bronze=len(np.where(medals=="Bronze")[0])
print("No of bronze medals", bronze)


Medals:  ['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
No of gold medals 2
No of silver medals 2
No of bronze medals 2


Q10.
Given the matrix below, use np.where with a single condition to obtain the row and column indices of every element greater than 50, print those elements, and then replace them with 0 in a copy of the matrix while leaving the original untouched.

m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

In [39]:
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols=np.where(m>50)
moreThan50=m[rows, cols]
print("Marks More than 50:",lessThan50)

arr=m.copy()
arr=np.where(arr>50,0,arr)
print("updated marks:",arr)


Marks More than 50: [80 55 99 70]
updated marks: [[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]


Q11.
Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and separately stack them so that each sensor becomes a column. Print both shapes and confirm that one is the transpose of the other.

s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

In [ ]:
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

arr1=np.vstack((s1,s2,s3))
print("Shape in case 1:",arr1.shape)

arr2=np.hstack((s1.reshape(-1,1),s2.reshape(-1,1),s3.reshape(-1,1)))
print("Shape in case 2:",arr2.shape)

#arr1 shape=3,5
#arr2 shape=5,3

# As rows and cols are interchanged, hence, they are transpose to each other

Shape in case 1: (3, 5)
Shape in case 2: (5, 3)


Q12.
Create a random 6x6 matrix with seed = 1 and values between 1 and 100, then find the row-wise maximum and the column-wise minimum.

In [44]:
np.random.seed(1)
arr=np.random.randint(1,101, size=(6,6))
print("Random array:",arr)

rowMax=np.max(arr, axis=1)
colMin=np.min(arr, axis=0)

print("Row wise maximum:",rowMax)
print("Column wise minimum:",colMin)

Random array: [[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
Row wise maximum: [76 80 85 69 97 64]
Column wise minimum: [ 7  8 17  2 19  6]


Q13.
A and B are both 2x3 matrices. Compute A @ B.T and A.T @ B. Print the shape of each result and explain in a comment why both multiplications are legal while A @ B is not.

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])

arr1=A@B.T
arr2=A.T@B

print("Shape in case1:",arr1.shape)
print("Shape in case2:",arr2.shape)

# for dot product the column number of 1st matrix should be equal to row number of the 2nd matrix
# This condition is satisfied in both above multiplication whereas not in A @ B 

Q14.
Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column vectors, join them into a single two-column table, attach a third column holding each row's total, then multiply the three-column table by w = [0.5, 0.2, 0.3] to obtain one score per row. Finally use np.where to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of every intermediate array.

hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

In [50]:
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])
w=np.array([0.5, 0.2, 0.3])

w=w.reshape(-1,1)

hours=hours.reshape(-1,1)
attendance=attendance.reshape(-1,1)
arr=np.hstack((hours,attendance))
print("Shape 1",arr.shape)

col3=np.sum(arr,axis=1).reshape(-1,1)
newArr=np.hstack((arr,col3))
print("Shape 2", newArr.shape)

score=newArr@w
avgScore=np.mean(score)

score=np.where(score>avgScore, 1, 0)
print("Score Array:",score)


Shape 1 (6, 2)
Shape 2 (6, 3)
Score Array: [[0]
 [1]
 [0]
 [1]
 [0]
 [1]]


Q15.
Apply min-max normalization to scale any array into the 0 to 1 range using (x - min) / (max - min).

In [ ]:
X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

col_min=X.min(axis=0)
col_max=X.max(axis=0)

arr=(X-col_min)/(col_max-col_min)
print(arr)

Q16.
Take the array below and create two 1D versions of it — one with flatten() and one with ravel(). Change the first element of each, then print the original matrix. Explain the difference you observe in a comment.

m = np.array([[4, 8, 15],
              [16, 23, 42]])

In [ ]:
m = np.array([[4, 8, 15],
              [16, 23, 42]])

mview=m.ravel()
mcopy=m.flatten()

mview[0]=100
mcopy[0]=200

print("Original Array:",m)

#ravel()=> create a view; points to same memory as original array
#flatten()=> creates a copy; creates a new memory for itself

Q17.
28 daily temperature readings are given. Reshape them into 4 weeks of 7 days, then: find each week's average, identify the hottest week, and count how many individual days crossed 35 degrees.

np.random.seed(7)
temps = np.random.randint(15, 41, 28)


In [51]:
np.random.seed(7)
temps = np.random.randint(15, 41, 28)

temps=temps.reshape(4,7)
weekAvg=np.mean(temps, axis=1)
print("The week averages:",weekAvg)

hottestWeek=np.argmax(weekAvg)
print("Hottest Week: ",hottestWeek+1)

countDays=np.sum(temps>35)
print("Count of days with 35 cross temperature:",countDays)

The week averages: [30.85714286 31.57142857 23.28571429 26.85714286]
Hottest Week:  2
Count of days with 35 cross temperature: 7


Q18.
Create two random 3x3 matrices A and B, compute A @ B and B @ A, and check whether the two results are equal. State your conclusion about matrix multiplication in a comment.

In [ ]:
arr1=np.random.rand((3,3))
arr2=np.random.rand((3,3))

print("Ans1:", arr1@arr2)
print("Ans2:",arr2@arr1)

Given the marks matrix below (5 students x 4 subjects), first replace every mark below 35 with 35, then compute each student's total, and finally print the index of the topper along with their total.

marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

In [52]:
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

marks=np.where(marks<35,35,marks)
total=np.sum(marks, axis=1)
maxTotal=np.argmax(total)

print("Topper idx:", maxTotal)
print("Total of topper:", total[maxTotal])

Topper idx: 3
Total of topper: 342


Q20.
Start from arr = np.arange(1, 11). Create one variable using a plain slice arr[2:6] and another using arr[2:6].copy(). Change the first element of each to 999, then print the original array and explain in a comment which change survived and why.

In [53]:
arr = np.arange(1, 11)
a=arr[2:6] #create a view of original array
b=arr[2:6].copy() # create a copy of the original array

a[0]=999
b[0]=100
print(arr)

[  1   2 999   4   5   6   7   8   9  10]


Q21.
Explore np.diag in the NumPy documentation and use it to extract the diagonal of a 4x4 matrix. Then use the same function in its second role — to build a diagonal matrix from a 1D array.

In [55]:
arr=np.arange(1,17).reshape(4,4)
diagonal=np.diag(arr)
print("Diagonal elements:", diagonal)

mat=np.diag(diagonal)
print("Matrix:",mat)

Diagonal elements: [ 1  6 11 16]
Matrix: [[ 1  0  0  0]
 [ 0  6  0  0]
 [ 0  0 11  0]
 [ 0  0  0 16]]
